---
development:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME: 'app/infrastructure/database/local/dev.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku

app_test:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REPOSTORE_PATH: app/infrastructure/git/repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku

test:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME: 'app/infrastructure/database/local/test.db'
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku

production:
  API_HOST: http://localhost:9000
  # Infrastructure
  # - assign DATABASE_URL in production
  UDEMY_TOKEN: This_Is_A_Sample_Udemy_Token
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku